# Generated by Django 3.0.1 on 2022-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myexperiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('comment1', models.TextField()),
                ('comment2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='myservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='myskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('comanyname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('comment', models.TextField()),
            ],
        ),
    ]
